# Generated by Django 5.1.3 on 2024-11-14 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medchainapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='medchainapi.doctor'),
        ),
    ]
